name: 'Simple Unity Test'
description: 'Run Unity Play Mode and Editor Mode Tests'

inputs:
  unityPath:
    description: 'The full path to the Unity executable.'
    required: true
    
  projectPath:
    description: 'The path to the project root.'
    default: '.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Unity Play Mode Test
      shell: cmd
      run: |
        "${{ inputs.unityPath }}" -batchmode -projectPath ${{ inputs.projectPath }} -runTests -testPlatform PlayMode -testResults TestResult-PlayMode.xml -logFile -

    - name: Unity Editor Mode Test
      shell: cmd
      run: |
        "${{ inputs.unityPath }}" -batchmode -projectPath ${{ inputs.projectPath }} -runTests -testPlatform EditMode -testResults TestResult-EditMode.xml -logFile -

    - name: Upload Test Results
      if: always()  
      uses: actions/upload-artifact@v3
      with:
        name: Test Results
        path: |
          TestResult-PlayMode.xml
          TestResult-EditMode.xml

    - name: Delete XML Test Results
      if: always()   
      shell: cmd
      run: |
        del "TestResult-PlayMode.xml" "TestResult-EditMode.xml"

branding:
  icon: 'arrow-up-circle'
  color: 'gray-dark'
